/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description: 'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
    instructions: `Verify that an implementation matches the change artifacts (specs, tasks, design).

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name. Add \`--adversarial\` to opt into a deeper falsification pass (for example, \`/opsx:verify add-auth --adversarial\`). Parse \`--adversarial\` as workflow input before change selection: remove it from the positional input, never treat it as a change name, and never append it to any \`openspec\` CLI command. If the flag is absent, run the standard verification only. If the change name is omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name remains after removing workflow flags, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and ask the user to select one

   When prompting, show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:verify <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - Which artifacts exist for this change

3. **Get planning context and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and \`contextFiles\` (artifact ID -> array of concrete file paths). Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If \`contextFiles.tasks\` exists, read every file path in it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`contextFiles.specs\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If \`contextFiles.design\` exists:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Optional adversarial pass (\`--adversarial\` only)**

   If \`--adversarial\` was not provided, skip this entire step. Do not spend tokens on adversarial claim selection, counterexample search, or extra validation.

   When enabled, reuse the evidence already gathered above rather than repeating broad discovery.

   **Build a bounded claim set**:
   - Inventory behavioral claims from requirements, scenarios, completed task outcomes, and explicit design decisions
   - Prioritize claims touching changed implementation paths first, then high-risk boundaries/error paths and cross-component behavior, then other contract-important claims
   - Review at most 5 important claims in one invocation; if fewer than 5 important claims exist, review all of them
   - Record important claims beyond the budget as \`UNCHECKED\`; summarize lower-priority unchecked claims too, so the report never implies exhaustive coverage

   **Try to falsify each selected claim**:
   - Trace the actual execution path instead of treating symbol/keyword presence as proof
   - Inspect whether relevant tests assert the required outcome instead of treating a passing suite as proof
   - Try a plausible boundary, negative/error, alternate-state, or cross-component counterexample
   - When practical, run the smallest focused executable validation that could disprove the claim
   - Classify the result as \`FAILED\`, \`WEAK EVIDENCE\`, \`SUPPORTED\`, or \`UNVERIFIED\`
   - Every \`FAILED\` result must cite the artifact claim, contradicting implementation/test evidence, and concrete failure mechanism
   - Missing tooling or environment produces \`UNVERIFIED\`, not an invented defect

   **Determine adversarial readiness from claim outcomes, not issue severity**:
   - Any \`FAILED\` important claim -> **Not ready**
   - Any important \`WEAK EVIDENCE\` or \`UNVERIFIED\` claim -> **Partially verified — not ready**
   - Any important claim left \`UNCHECKED\` because of the budget -> **Partially verified — not ready**
   - **Ready** only when every important claim is \`SUPPORTED\`; lower-priority \`UNCHECKED\` remainder may exist but must be reported explicitly

9. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`markdown
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

   **Adversarial Assessment** (\`--adversarial\` only):
   - Add a compact checked-claims table with each selected claim and its \`FAILED\`, \`WEAK EVIDENCE\`, \`SUPPORTED\`, or \`UNVERIFIED\` outcome
   - Add an \`UNCHECKED\` remainder section, distinguishing important claims skipped because of the budget from lower-priority claims not selected
   - End with the adversarial readiness from claim outcomes above. This readiness is independent of CRITICAL/WARNING/SUGGESTION issue counts
   - Do not use the baseline "All checks passed" terminal line as the adversarial readiness result

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: `Verify that an implementation matches the change artifacts (specs, tasks, design).

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name after \`/opsx:verify\` (e.g., \`/opsx:verify add-auth\`). Add \`--adversarial\` anywhere after the command to opt into a deeper falsification pass (e.g., \`/opsx:verify add-auth --adversarial\`). Parse \`--adversarial\` as workflow input before change selection: remove it from the positional input, never treat it as a change name, and never append it to any \`openspec\` CLI command. If the flag is absent, run the standard verification only. If the change name is omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name remains after removing workflow flags, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and ask the user to select one

   When prompting, show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:verify <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - Which artifacts exist for this change

3. **Get planning context and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and \`contextFiles\` (artifact ID -> array of concrete file paths). Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If \`contextFiles.tasks\` exists, read every file path in it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`contextFiles.specs\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If \`contextFiles.design\` exists:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Optional adversarial pass (\`--adversarial\` only)**

   If \`--adversarial\` was not provided, skip this entire step. Do not spend tokens on adversarial claim selection, counterexample search, or extra validation.

   When enabled, reuse the evidence already gathered above rather than repeating broad discovery.

   **Build a bounded claim set**:
   - Inventory behavioral claims from requirements, scenarios, completed task outcomes, and explicit design decisions
   - Prioritize claims touching changed implementation paths first, then high-risk boundaries/error paths and cross-component behavior, then other contract-important claims
   - Review at most 5 important claims in one invocation; if fewer than 5 important claims exist, review all of them
   - Record important claims beyond the budget as \`UNCHECKED\`; summarize lower-priority unchecked claims too, so the report never implies exhaustive coverage

   **Try to falsify each selected claim**:
   - Trace the actual execution path instead of treating symbol/keyword presence as proof
   - Inspect whether relevant tests assert the required outcome instead of treating a passing suite as proof
   - Try a plausible boundary, negative/error, alternate-state, or cross-component counterexample
   - When practical, run the smallest focused executable validation that could disprove the claim
   - Classify the result as \`FAILED\`, \`WEAK EVIDENCE\`, \`SUPPORTED\`, or \`UNVERIFIED\`
   - Every \`FAILED\` result must cite the artifact claim, contradicting implementation/test evidence, and concrete failure mechanism
   - Missing tooling or environment produces \`UNVERIFIED\`, not an invented defect

   **Determine adversarial readiness from claim outcomes, not issue severity**:
   - Any \`FAILED\` important claim -> **Not ready**
   - Any important \`WEAK EVIDENCE\` or \`UNVERIFIED\` claim -> **Partially verified — not ready**
   - Any important claim left \`UNCHECKED\` because of the budget -> **Partially verified — not ready**
   - **Ready** only when every important claim is \`SUPPORTED\`; lower-priority \`UNCHECKED\` remainder may exist but must be reported explicitly

9. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`markdown
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

   **Adversarial Assessment** (\`--adversarial\` only):
   - Add a compact checked-claims table with each selected claim and its \`FAILED\`, \`WEAK EVIDENCE\`, \`SUPPORTED\`, or \`UNVERIFIED\` outcome
   - Add an \`UNCHECKED\` remainder section, distinguishing important claims skipped because of the budget from lower-priority claims not selected
   - End with the adversarial readiness from claim outcomes above. This readiness is independent of CRITICAL/WARNING/SUGGESTION issue counts
   - Do not use the baseline "All checks passed" terminal line as the adversarial readiness result

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`
  };
}
